from .int_to_float_node import NODE_CLASS_MAPPINGS as INT_TO_FLOAT_MAPPINGS
from .float_to_int_node import NODE_CLASS_MAPPINGS as FLOAT_TO_INT_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(INT_TO_FLOAT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FLOAT_TO_INT_MAPPINGS)